version: '3'

services:
  # Application php-fpm container
  application:
    container_name: ${PROJECT_NAME}_python
    build: .
    working_dir: /app
    restart: always
    volumes:
      - ${PROJECT_PATH}:/app
    environment:
      - PORT=${WEB_PORT}
      - DB_URL=mysql+pymysql://${DB_USER}:${DB_PASS}@192.168.1.48:13306/${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - PSK=${PSK}
    ports:
      - '${WEB_PORT}:5000'