version: '3'

services:
  # Application php-fpm container
  application:
    container_name: ${PROJECT_NAME}_python
    build: .
    working_dir: /app
    depends_on:
      - database
    restart: always
    volumes:
      - ${PROJECT_PATH}:/app
    environment:
      - PORT=${WEB_PORT}
      - DB_URL=mysql+pymysql://${DB_USER}:${DB_PASS}@${PROJECT_NAME}_mariadb:3306/${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - PSK=${PSK}
    ports:
      - '${WEB_PORT}:5000'

  # Mariadb database image
  database:
    container_name: ${PROJECT_NAME}_mariadb
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASS}
      - MARIADB_ROOT_PASSWORD=${DB_PASS}
      - ALLOW_EMPTY_PASSWORD=${DB_ALLOW_EMPTY_PASSWORD:-no}
      - TZ=${TIME_ZONE}
    volumes:
      - db-store:/bitnami/mariadb
    restart: always
    ports:
      - '${DB_PORT}:3306'

volumes:
  db-store:
